### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by raucao** [lesion/remotestorage-module-bookmarks#3]
I think this module hasn't been published to npm yet.

Would be nice if I could switch Webmarks from the GitHub dependency of my fork to an actual npm module with version numbers. Same for other apps using bookmarks. (Planning to add bookmarks to https://github.com/67P/hyperchannel soon for example.)

**Comment by lesion** [comment]
https://www.npmjs.com/package/remotestorage-module-bookmarks
also searchable https://www.npmjs.com/search?q=remotestorage-module
